### ISSUE TITLE
Sharing the checkpoint

### ISSUE THREAD

**Issue by Kingofolk** [kalelpark/RAL#2]
Hi!

Thanks for your great work! I am writing to inquire that would you mind sharing me with the checkpoint? Looking forward to your reply!

Best regards
Kingofolk

**Comment by WongiPark0628** [comment]
Thanks for your interest. 
Unfortunately, It has been a long time since I participated in the competition, and I no longer have it.

Thank you for your interest and for leaving the issue.
If you have any questions, feel free to ask me.
